### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by vovanb** [JasonSowers/ChatHistoryBot-Public#1]
Can you please provide readme how to use this project?

**Comment by JasonSowers** [comment]
@vovanb Yes It is on my todo list, thanks for reminding me

**Comment by JasonSowers** [comment]
@vovanb I have added instructions to the readme but have not tested them yet.  Let me know if it makes sense, works for you, and if I need to put more details in there.  Thanks again for reminding me to do this 🥇
